import { expect, test } from '@playwright/test'

test('posts a real isolated batch, explores results, and downloads the report', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByText('Ready to run', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Run Payroll', exact: true }).first().click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByText('Ready to run', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Run Payroll', exact: true }).first().click()
  await page.getByRole('button', { name: 'Confirm payroll' }).click()
  await expect(page.getByRole('status')).toContainText('Payroll posted successfully')
  await expect(page.getByRole('button', { name: 'Run Payroll', exact: true })).toBeDisabled()
  await expect(page.locator('.employee-table tbody tr')).toHaveCount(3)
  await expect(page.locator('.net-metric')).toContainText('$3,132.99')
  await page.getByRole('button', { name: 'View Alex Morgan details' }).click()
  await expect(page.getByRole('dialog')).toContainText('$1,068.83')
  await page.getByRole('button', { name: 'Close employee details' }).click()
  await page.getByRole('textbox', { name: 'Search employees' }).fill('Jordan')
  await expect(page.locator('.employee-table tbody tr')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'Search employees' }).fill('missing')
  await expect(page.getByText('No matching employees')).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByLabel('Filter by department').selectOption('ENG')
  await expect(page.locator('.employee-table tbody tr')).toHaveCount(2)
  await page.getByLabel('Filter by department').selectOption('all')
  await page.getByLabel('Sort employees').selectOption('net')
  await expect(page.locator('.employee-table tbody tr').first()).toContainText('Sam Patel')
  await page.getByRole('tab', { name: 'Departments', exact: true }).click()
  await expect(page.locator('.department-section')).toContainText('$3,468.75')
  await page.getByRole('tab', { name: 'General ledger', exact: true }).click()
  await expect(page.locator('.ledger-section')).toContainText('Balanced')
  await page.getByText('Individual ledger entries', { exact: false }).first().click()
  await expect(page.locator('.ledger-details tbody tr')).toHaveCount(15)
  await page.getByRole('tab', { name: 'Print report', exact: true }).click()
  await expect(page.locator('pre')).toContainText('GRAND TOTAL')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export report' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('payroll_report_20260915.txt')
  await page.getByRole('tab', { name: /Payroll register/ }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true, animations: 'disabled' })
  expect(await page.locator('.brand img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  expect(errors).toEqual([])
})

test('demo, loading, error and empty states remain usable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('radio', { name: 'Demo data' }).check()
  await expect(page.locator('.employee-table tbody tr')).toHaveCount(3)
  await page.getByRole('button', { name: 'Run demo', exact: true }).click()
  await page.getByRole('button', { name: 'Run demo', exact: true }).last().click()
  await expect(page.getByRole('status')).toContainText('No ledger entries were posted')
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const overflowing = await page.locator('.metric > strong, .button, h1').evaluateAll(elements => elements.filter(element => element.scrollWidth > element.clientWidth).map(element => element.textContent))
  expect(overflowing).toEqual([])
  await page.route('**/api/payroll', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'Fixture database unavailable' }) }))
  await page.getByRole('radio', { name: 'Local batch' }).check()
  await expect(page.getByRole('alert')).toContainText('Fixture database unavailable')
  await expect(page.locator('.employee-table tbody tr')).toHaveCount(0)
  await expect(page.locator('.net-metric')).toContainText('$0.00')
  await page.unroute('**/api/payroll')
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/payroll', async route => {
    await gate
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ source: 'local', status: 'empty', period: null, inputPeriod: null, generatedAt: null, canRun: false, reason: 'No input batch.', employees: [], ledger: [], report: '' }) })
  })
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Loading payroll data')
  release()
  await expect(page.getByText('No payroll results yet')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open demo dataset' })).toBeVisible()
})